/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as MedicalProfileRouteImport } from './routes/medical-profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationRouteImport } from './routes/location'
import { Route as LinkRouteImport } from './routes/link'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HospitalsPlaceIdRouteImport } from './routes/hospitals.$placeId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalProfileRoute = MedicalProfileRouteImport.update({
  id: '/medical-profile',
  path: '/medical-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsPlaceIdRoute = HospitalsPlaceIdRouteImport.update({
  id: '/$placeId',
  path: '/$placeId',
  getParentRoute: () => HospitalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/history': typeof HistoryRoute
  '/hospitals': typeof HospitalsRouteWithChildren
  '/link': typeof LinkRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/medical-profile': typeof MedicalProfileRoute
  '/medications': typeof MedicationsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hospitals/$placeId': typeof HospitalsPlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/history': typeof HistoryRoute
  '/hospitals': typeof HospitalsRouteWithChildren
  '/link': typeof LinkRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/medical-profile': typeof MedicalProfileRoute
  '/medications': typeof MedicationsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hospitals/$placeId': typeof HospitalsPlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/contacts': typeof ContactsRoute
  '/dashboard': typeof DashboardRoute
  '/emergency': typeof EmergencyRoute
  '/history': typeof HistoryRoute
  '/hospitals': typeof HospitalsRouteWithChildren
  '/link': typeof LinkRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/medical-profile': typeof MedicalProfileRoute
  '/medications': typeof MedicationsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/plans': typeof PlansRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/hospitals/$placeId': typeof HospitalsPlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/auth'
    | '/contacts'
    | '/dashboard'
    | '/emergency'
    | '/history'
    | '/hospitals'
    | '/link'
    | '/location'
    | '/login'
    | '/medical-profile'
    | '/medications'
    | '/notifications'
    | '/onboarding'
    | '/plans'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/hospitals/$placeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/auth'
    | '/contacts'
    | '/dashboard'
    | '/emergency'
    | '/history'
    | '/hospitals'
    | '/link'
    | '/location'
    | '/login'
    | '/medical-profile'
    | '/medications'
    | '/notifications'
    | '/onboarding'
    | '/plans'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/hospitals/$placeId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/auth'
    | '/contacts'
    | '/dashboard'
    | '/emergency'
    | '/history'
    | '/hospitals'
    | '/link'
    | '/location'
    | '/login'
    | '/medical-profile'
    | '/medications'
    | '/notifications'
    | '/onboarding'
    | '/plans'
    | '/register'
    | '/settings'
    | '/sitemap.xml'
    | '/hospitals/$placeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  ContactsRoute: typeof ContactsRoute
  DashboardRoute: typeof DashboardRoute
  EmergencyRoute: typeof EmergencyRoute
  HistoryRoute: typeof HistoryRoute
  HospitalsRoute: typeof HospitalsRouteWithChildren
  LinkRoute: typeof LinkRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  MedicalProfileRoute: typeof MedicalProfileRoute
  MedicationsRoute: typeof MedicationsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PlansRoute: typeof PlansRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-profile': {
      id: '/medical-profile'
      path: '/medical-profile'
      fullPath: '/medical-profile'
      preLoaderRoute: typeof MedicalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals/$placeId': {
      id: '/hospitals/$placeId'
      path: '/$placeId'
      fullPath: '/hospitals/$placeId'
      preLoaderRoute: typeof HospitalsPlaceIdRouteImport
      parentRoute: typeof HospitalsRoute
    }
  }
}

interface HospitalsRouteChildren {
  HospitalsPlaceIdRoute: typeof HospitalsPlaceIdRoute
}

const HospitalsRouteChildren: HospitalsRouteChildren = {
  HospitalsPlaceIdRoute: HospitalsPlaceIdRoute,
}

const HospitalsRouteWithChildren = HospitalsRoute._addFileChildren(
  HospitalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  ContactsRoute: ContactsRoute,
  DashboardRoute: DashboardRoute,
  EmergencyRoute: EmergencyRoute,
  HistoryRoute: HistoryRoute,
  HospitalsRoute: HospitalsRouteWithChildren,
  LinkRoute: LinkRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  MedicalProfileRoute: MedicalProfileRoute,
  MedicationsRoute: MedicationsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PlansRoute: PlansRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
